#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW_ROOT="${RAW_ROOT:-/home/jinlin/data/geoexplicit_data}"
DATA_ROOT="${DATA_ROOT:-$RAW_ROOT/synthetic_city/data}"
PYTHON_BIN="${PYTHON_BIN:-python}"

JOINT_WIDE_CSV="${JOINT_WIDE_CSV:-$DATA_ROOT/us/processed/external_targets/exttarget_v1_full_earn_pums_2023_puma_us_joint_wide.csv}"
SCHEMA_JSON="${SCHEMA_JSON:-$DATA_ROOT/us/processed/external_targets/exttarget_v1_full_earn_pums_2023_puma_us.schema.json}"
CONDITION_CSV="${CONDITION_CSV:-$DATA_ROOT/us/processed/external_conditions/extcond_v1_earn_v1_acs5_2022_puma_us.csv}"
CONDITION_SCHEMA_JSON="${CONDITION_SCHEMA_JSON:-$SCHEMA_JSON}"

TIMESTEPS="${TIMESTEPS:-200}"
EPOCHS="${EPOCHS:-600}"
BATCH_SIZE="${BATCH_SIZE:-1024}"
ENCODER_HIDDEN_DIMS="${ENCODER_HIDDEN_DIMS:-256,256}"
COARSE_HIDDEN_DIMS="${COARSE_HIDDEN_DIMS:-256}"
DIFFUSION_HIDDEN_DIMS="${DIFFUSION_HIDDEN_DIMS:-512,512}"
LATENT_DIM="${LATENT_DIM:-128}"
LR="${LR:-1e-3}"
WEIGHT_DECAY="${WEIGHT_DECAY:-1e-4}"
CONDITION_INJECTION="${CONDITION_INJECTION:-concat}"
FILM_HIDDEN_DIM="${FILM_HIDDEN_DIM:-128}"
DIFFUSION_WEIGHT="${DIFFUSION_WEIGHT:-1.0}"
MARGINAL_WEIGHT="${MARGINAL_WEIGHT:-0.0}"
COARSE_HEAD_WEIGHT="${COARSE_HEAD_WEIGHT:-0.0}"
CONSISTENCY_WEIGHT="${CONSISTENCY_WEIGHT:-0.0}"
AUX_T_GATE="${AUX_T_GATE:--1}"
TEACHER_STAGE1_CHECKPOINT="${TEACHER_STAGE1_CHECKPOINT:-}"
DISTILL_WEIGHT="${DISTILL_WEIGHT:-0.0}"
DISTILL_TEMPERATURE="${DISTILL_TEMPERATURE:-1.0}"
TEACHER_BATCH_SIZE="${TEACHER_BATCH_SIZE:-4096}"
PREDICT_MODE="${PREDICT_MODE:-diffusion}"
RUN_LABEL="${RUN_LABEL:-external_c2f_full_earn_stage1_coarse_diffusion}"
SELECTION_METRIC="${SELECTION_METRIC:-val_tvd_joint}"
SELECTION_RAW_WEIGHT="${SELECTION_RAW_WEIGHT:-0.25}"
LOGP_CLIP_QUANTILE_LOW="${LOGP_CLIP_QUANTILE_LOW:--1}"
LOGP_CLIP_QUANTILE_HIGH="${LOGP_CLIP_QUANTILE_HIGH:--1}"
LOG_EVERY="${LOG_EVERY:-200}"
EVAL_EVERY="${EVAL_EVERY:-50}"
VAL_FRAC="${VAL_FRAC:-0.05}"
VAL_MIN_GROUPS="${VAL_MIN_GROUPS:-96}"
N_VAL_JOINT_SAMPLES="${N_VAL_JOINT_SAMPLES:-64}"
N_EVAL_JOINT_SAMPLES="${N_EVAL_JOINT_SAMPLES:-64}"
IPF_ITERS="${IPF_ITERS:-200}"
EMA_DECAY="${EMA_DECAY:-0.999}"
DEVICE="${DEVICE:-cuda}"
SEED="${SEED:-0}"
RUN_DIR="${RUN_DIR:-outputs/_us_puma_external_c2f_full_earn_stage1_coarse_diffusion_$(date -u +%Y%m%dT%H%M%SZ)}"

cd "$ROOT_DIR"

CMD=(
  "$PYTHON_BIN" -u tools/train_external_c2f_full_earn_stage1_coarse.py
  --joint_wide_csv "$JOINT_WIDE_CSV"
  --condition_csv "$CONDITION_CSV"
  --schema_json "$SCHEMA_JSON"
  --condition_schema_json "$CONDITION_SCHEMA_JSON"
  --timesteps "$TIMESTEPS"
  --epochs "$EPOCHS"
  --batch_size "$BATCH_SIZE"
  --encoder_hidden_dims "$ENCODER_HIDDEN_DIMS"
  --coarse_hidden_dims "$COARSE_HIDDEN_DIMS"
  --diffusion_hidden_dims "$DIFFUSION_HIDDEN_DIMS"
  --latent_dim "$LATENT_DIM"
  --lr "$LR"
  --weight_decay "$WEIGHT_DECAY"
  --condition_injection "$CONDITION_INJECTION"
  --film_hidden_dim "$FILM_HIDDEN_DIM"
  --diffusion_weight "$DIFFUSION_WEIGHT"
  --marginal_weight "$MARGINAL_WEIGHT"
  --coarse_head_weight "$COARSE_HEAD_WEIGHT"
  --consistency_weight "$CONSISTENCY_WEIGHT"
  --aux_t_gate "$AUX_T_GATE"
  --distill_weight "$DISTILL_WEIGHT"
  --distill_temperature "$DISTILL_TEMPERATURE"
  --teacher_batch_size "$TEACHER_BATCH_SIZE"
  --predict_mode "$PREDICT_MODE"
  --run_label "$RUN_LABEL"
  --selection_metric "$SELECTION_METRIC"
  --selection_raw_weight "$SELECTION_RAW_WEIGHT"
  --logp_clip_quantile_low "$LOGP_CLIP_QUANTILE_LOW"
  --logp_clip_quantile_high "$LOGP_CLIP_QUANTILE_HIGH"
  --log_every "$LOG_EVERY"
  --eval_every "$EVAL_EVERY"
  --val_frac "$VAL_FRAC"
  --val_min_groups "$VAL_MIN_GROUPS"
  --n_val_joint_samples "$N_VAL_JOINT_SAMPLES"
  --n_eval_joint_samples "$N_EVAL_JOINT_SAMPLES"
  --ipf_iters "$IPF_ITERS"
  --ema_decay "$EMA_DECAY"
  --device "$DEVICE"
  --seed "$SEED"
  --save_best_checkpoint
  --save_final_model
  --out_dir "$RUN_DIR"
)
if [[ -n "$TEACHER_STAGE1_CHECKPOINT" ]]; then
  CMD+=(--teacher_stage1_checkpoint "$TEACHER_STAGE1_CHECKPOINT")
fi

printf '[info] CMD='
printf '%q ' "${CMD[@]}"
printf '\n'
"${CMD[@]}"
